### ISSUE TITLE
Running the code locally

### ISSUE THREAD

**Issue by tushartgupta** [xiaoxiae/videos#11]
Hello,
Great video explanations you have put. How can i run the code locally? I did the setup but when running the code i get these exceptions: Here i was trying to run the "01-lopt" code - 

manim -pql scenes.py Visualizepy
Manim Community v0.15.2

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/manim", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/manim/cli/render/commands.py", line 115, in render
    for SceneClass in scene_classes_from_file(file):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/manim/utils/module_ops.py", line 127, in scene_classes_from_file
    module = get_module(file_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/manim/utils/module_ops.py", line 52, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/tushar/Documents/manim/projects/videos-master/01-lopt/scenes.py", line 1, in <module>
    from utilities import *
  File "/Users/tushar/Documents/manim/projects/videos-master/01-lopt/utilities.py", line 7
    from utilities
                  ^
SyntaxError: invalid syntax

**Comment by xiaoxiae** [comment]
It seems like there was a typo in `utilities.py` that should be solved by the latest commit.
However, it seems that 01-lopt and some of the other older videos use deprecated classes and so will not build with the current version of Manim.

**Comment by tushartgupta** [comment]
Thanks. Will check.
